### ISSUE TITLE
Add Ollama or any local LLM models

### ISSUE THREAD

**Issue by bmabir17** [Gamingpro237/Advanced_Interview_responder_with_AI#1]
Hi, 
i really loved the idea, can we also have ollama or any other locally hosted llms. As it might get very costly very fast if it keeps using openai API

**Comment by Gamingpro237** [comment]
Good idea. Alright, I'm going to add different models, in such a way the user can choose the one he/she have, in order to used

**Comment by Gamingpro237** [comment]
Now it has been solved
